CREATE TABLE Address(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    STREET VARCHAR(50) NOT NULL,
    CITY VARCHAR(20),
    STATE VARCHAR(2),
    ZIP VARCHAR(5) NOT NULL
) AUTO_INCREMENT = 100;

CREATE TABLE Customer(
	ID BIGINT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    FIRST_NAME VARCHAR(10) NOT NULL,
    LAST_NAME VARCHAR(10) NOT NULL,
    DOB TIMESTAMP NOT NULL,
    GENDER VARCHAR(1) NOT NULL,
    PHONE VARCHAR(15) NOT NULL,
    ADDRESS_ID INTEGER NOT NULL,
    FOREIGN KEY (ADDRESS_ID) REFERENCES Address(ID)
) AUTO_INCREMENT = 100;