INSERT INTO Address(STREET_1, CITY, STATE, ZIP, COUNTRY, CREATED_DATE, ACTIVE) VALUES ('1000 N 4th St', 'Fairfield', 'IA', '52556', 'US', NOW(), 1);
INSERT INTO Address(STREET_1, CITY, STATE, ZIP, COUNTRY, CREATED_DATE, ACTIVE) VALUES ('1000 Windsor Shores Dr', 'Columbia', 'SC', '29223', 'US', NOW(), 1);

INSERT INTO Authority(EMAIL, AUTHORITY, CREATED_DATE, ACTIVE) VALUES ('toanqc@gmail.com', 'ROLE_USER', NOW(), 1);
INSERT INTO Authority(EMAIL, AUTHORITY, CREATED_DATE, ACTIVE) VALUES ('trinh_nganha@yahoo.com', 'ROLE_USER', NOW(), 1);

INSERT INTO `User`(EMAIL, `PASSWORD`, CREATED_DATE, ACTIVE) VALUES ('toanqc@gmail.com', SHA2('toanquach', 256), NOW(), 1);
INSERT INTO `User`(EMAIL, `PASSWORD`, CREATED_DATE, ACTIVE) VALUES ('trinh_nganha@yahoo.com', SHA2('hatrinh', 256), NOW(), 1);

INSERT INTO Account(ACCOUNT_ID, FIRST_NAME, LAST_NAME, GENDER, PHONE, EMAIL, ACTIVE, ADDRESS_ID, USER_ID, CREATED_DATE) VALUES ('A-0001','Toan', 'Quach', 'M', '111-111-1111', 'toanqc@gmail.com', 1, 1, 1, NOW());
INSERT INTO Account(ACCOUNT_ID, FIRST_NAME, LAST_NAME, GENDER, PHONE, EMAIL, ACTIVE, ADDRESS_ID, USER_ID, CREATED_DATE) VALUES ('A-0002', 'Ha', 'Trinh', 'F', '222-222-2222', 'trinh_nganha@yahoo.com', 1, 2, 2, NOW());